project:
  type: website
  output-dir: docs
  resources: 
   - "d_fig/**"

website:
  title: "SatCSF"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cities.qmd
        text: Cities

format:
  html:
    theme: cosmo       # try: cosmo, flatly, litera, journal, pulse
    toc: true
    toc-depth: 2

